{% set name = "bw2analyzer" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9f48998e249d91f89fe5e100dc41cdb2169f9ced0da56695837f0552b39de74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools
  run:
    - bw2calc
    - bw2data
    - matplotlib-base
    - numpy
    - pandas
    - pyprind
    - python >=3.4
    - requests
    - scipy
    - stats_arrays
    - tabulate

test:
  imports:
    - bw2analyzer

about:
  home: https://github.com/brightway-lca/brightway2-analyzer
  summary: Set of tools to analyze results of life cycle assessment (LCA) calculations
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-analyzer

extra:
  recipe-maintainers:
    - m-rossi
